In [1]:
import pandas as pd
import  matplotlib.pyplot as plt

In [76]:
#1
#A
dfConfirmados = pd.read_csv('data/covid19_confirmados.csv', index_col="Country/Region")
#B
del dfConfirmados["Lat"]
del dfConfirmados["Long"]
#C
for i in range(1,461):
    dfConfirmados = dfConfirmados.rename(columns={dfConfirmados.columns[i]:pd.to_datetime(dfConfirmados.columns[i]).strftime('%d/%m/%Y') })

#D
del dfConfirmados["Province/State"]
dfConfirmados = dfConfirmados.groupby(by=['Country/Region']).sum()
dfConfirmados = dfConfirmados.sort_values('Country/Region')
display(dfConfirmados)

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,16/04/2021,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,57612,57721,57793,57898,58037,58214,58312,58542,58730,58843
Albania,0,0,0,0,0,0,0,0,0,0,...,129307,129456,129594,129694,129842,129980,130114,130270,130409,130537
Algeria,0,0,0,0,0,0,0,0,0,0,...,119323,119486,119642,119805,119992,120174,120363,120562,120736,120922
Andorra,0,0,0,0,0,0,0,0,0,0,...,12712,12771,12805,12805,12874,12917,12942,13007,13024,13060
Angola,0,0,0,0,0,0,0,0,0,0,...,24122,24300,24389,24518,24661,24883,25051,25279,25492,25609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0,2,2,2,2,2,2,2,2,2,...,2772,2781,2785,2791,2800,2812,2824,2830,2833,2843
West Bank and Gaza,0,0,0,0,0,0,0,0,0,0,...,278135,279753,280741,282270,284280,286028,287680,289120,290259,290972
Yemen,0,0,0,0,0,0,0,0,0,0,...,5715,5770,5812,5858,5918,5960,6020,6056,6105,6137
Zambia,0,0,0,0,0,0,0,0,0,0,...,90750,90844,90918,90942,91042,91119,91189,91251,91317,91358
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,37534,37699,37751,37859,37875,37980,38018,38045,38064,38086

In [3]:
dfPopulation = pd.read_csv('data/population_by_country_2020.csv', index_col="Country/Region")
dfPopulation = dfPopulation.sort_values('Country/Region')
display(dfPopulation)

,Population (2020),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
Country/Region,,,,,,,,,,
Afghanistan,39074280,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %
Albania,2877239,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Algeria,43984569,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
American Samoa,55169,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
Andorra,77287,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...
Wallis & Futuna,11203,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
Western Sahara,599769,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Yemen,29935468,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Zambia,18468257,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Zimbabwe,14899771,1.48 %,217456,38,386850,-116858.0,3.6,19,38 %,0.19 %

In [4]:
dfConfirmadosPopulation = pd.merge(dfConfirmados,dfPopulation[['Population (2020)']], on="Country/Region")
display(dfConfirmadosPopulation)

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021,Population (2020)
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,57721,57793,57898,58037,58214,58312,58542,58730,58843,39074280
Albania,0,0,0,0,0,0,0,0,0,0,...,129456,129594,129694,129842,129980,130114,130270,130409,130537,2877239
Algeria,0,0,0,0,0,0,0,0,0,0,...,119486,119642,119805,119992,120174,120363,120562,120736,120922,43984569
Andorra,0,0,0,0,0,0,0,0,0,0,...,12771,12805,12805,12874,12917,12942,13007,13024,13060,77287
Angola,0,0,0,0,0,0,0,0,0,0,...,24300,24389,24518,24661,24883,25051,25279,25492,25609,33032075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,0,...,181903,183190,184595,185736,186745,188063,189381,190523,191518,28421581
Vietnam,0,2,2,2,2,2,2,2,2,2,...,2781,2785,2791,2800,2812,2824,2830,2833,2843,97490013
Yemen,0,0,0,0,0,0,0,0,0,0,...,5770,5812,5858,5918,5960,6020,6056,6105,6137,29935468
Zambia,0,0,0,0,0,0,0,0,0,0,...,90844,90918,90942,91042,91119,91189,91251,91317,91358,18468257
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,37699,37751,37859,37875,37980,38018,38045,38064,38086,14899771

In [5]:
dfConfirmadosPopulationUnion = pd.merge(dfConfirmados,dfPopulation[['Population (2020)']], on="Country/Region", how='outer')
noEstan = []
for i in range(0,len(dfConfirmadosPopulationUnion.index)):
    if not (dfConfirmadosPopulationUnion.index[i] in dfConfirmadosPopulation.index):
        noEstan.append(dfConfirmadosPopulationUnion.index[i])

print('En las siguientes filas no se pudo realizar merge: ')
print(noEstan)

En las siguientes filas no se pudo realizar merge:
['Burma', 'Diamond Princess', 'Kosovo', 'MS Zaandam', 'Saint Vincent and the Grenadines', 'West Bank and Gaza', 'American Samoa', 'Anguilla', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Caribbean Netherlands', 'Cayman Islands', 'Channel Islands', 'Cook Islands', 'Curaçao', 'Faeroe Islands', 'Falkland Islands', 'French Guiana', 'French Polynesia', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Hong Kong', 'Isle of Man', 'Kiribati', 'Macao', 'Martinique', 'Mayotte', 'Montserrat', 'Myanmar', 'Nauru', 'New Caledonia', 'Niue', 'North Korea', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'Réunion', 'Saint Barthelemy', 'Saint Helena', 'Saint Martin', 'Saint Pierre & Miquelon', 'Sint Maarten', 'St. Vincent & Grenadines', 'State of Palestine', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos', 'Tuvalu', 'U.S. Virgin Islands', 'Wallis & Futuna', 'Western Sahara']

In [6]:
#1
#A
dfRecuperados = pd.read_csv('data/covid19_recuperados.csv', index_col="Country/Region")
#B
del dfRecuperados["Lat"]
del dfRecuperados["Long"]
#C
for i in range(1,461):
    dfRecuperados = dfRecuperados.rename(columns={dfRecuperados.columns[i]:pd.to_datetime(dfRecuperados.columns[i]).strftime('%d/%m/%Y') })
    
#D
del dfRecuperados["Province/State"]
dfRecuperados = dfRecuperados.groupby(by=['Country/Region']).sum()
dfRecuperados = dfRecuperados.sort_values('Country/Region')
display(dfRecuperados)


dfRecuperadosPopulation = pd.merge(dfRecuperados,dfPopulation[['Population (2020)']], on="Country/Region")
display(dfRecuperadosPopulation)

dfRecuperadosPopulationUnion = pd.merge(dfRecuperados,dfPopulation[['Population (2020)']], on="Country/Region", how='outer')
noEstan = []
for i in range(0,len(dfRecuperadosPopulationUnion.index)):
    if not (dfRecuperadosPopulationUnion.index[i] in dfRecuperadosPopulation.index):
        noEstan.append(dfRecuperadosPopulationUnion.index[i])

print('En las siguientes filas no se pudo realizar merge: ')
print(noEstan)

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,16/04/2021,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,52105,52116,52168,52244,52272,52301,52348,52363,52392,52489
Albania,0,0,0,0,0,0,0,0,0,0,...,100600,101142,101584,102171,102601,103066,103582,104278,105016,105728
Algeria,0,0,0,0,0,0,0,0,0,0,...,83169,83286,83397,83514,83636,83765,83900,84038,84167,84299
Andorra,0,0,0,0,0,0,0,0,0,0,...,12105,12159,12203,12203,12285,12334,12375,12423,12458,12491
Angola,0,0,0,0,0,0,0,0,0,0,...,22203,22576,22597,22600,22647,22882,22901,23089,23092,23092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0,0,0,0,0,0,0,0,0,0,...,2445,2475,2475,2475,2490,2490,2490,2490,2490,2516
West Bank and Gaza,0,0,0,0,0,0,0,0,0,0,...,243522,245295,247359,249382,251663,254199,256559,259105,260650,262602
Yemen,0,0,0,0,0,0,0,0,0,0,...,2204,2209,2219,2261,2281,2309,2393,2454,2486,2546
Zambia,0,0,0,0,0,0,0,0,0,0,...,88414,88555,88718,88860,88900,88956,89117,89256,89403,89574
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,34981,35005,35019,35031,35058,35065,35073,35094,35101,35123

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021,Population (2020)
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,52116,52168,52244,52272,52301,52348,52363,52392,52489,39074280
Albania,0,0,0,0,0,0,0,0,0,0,...,101142,101584,102171,102601,103066,103582,104278,105016,105728,2877239
Algeria,0,0,0,0,0,0,0,0,0,0,...,83286,83397,83514,83636,83765,83900,84038,84167,84299,43984569
Andorra,0,0,0,0,0,0,0,0,0,0,...,12159,12203,12203,12285,12334,12375,12423,12458,12491,77287
Angola,0,0,0,0,0,0,0,0,0,0,...,22576,22597,22600,22647,22882,22901,23089,23092,23092,33032075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,0,...,164530,165959,166826,168418,169685,171043,172035,173097,173097,28421581
Vietnam,0,0,0,0,0,0,0,0,0,0,...,2475,2475,2475,2490,2490,2490,2490,2490,2516,97490013
Yemen,0,0,0,0,0,0,0,0,0,0,...,2209,2219,2261,2281,2309,2393,2454,2486,2546,29935468
Zambia,0,0,0,0,0,0,0,0,0,0,...,88555,88718,88860,88900,88956,89117,89256,89403,89574,18468257
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,35005,35019,35031,35058,35065,35073,35094,35101,35123,14899771

En las siguientes filas no se pudo realizar merge:
['Burma', 'Diamond Princess', 'Kosovo', 'MS Zaandam', 'Saint Vincent and the Grenadines', 'West Bank and Gaza', 'American Samoa', 'Anguilla', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Caribbean Netherlands', 'Cayman Islands', 'Channel Islands', 'Cook Islands', 'Curaçao', 'Faeroe Islands', 'Falkland Islands', 'French Guiana', 'French Polynesia', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Hong Kong', 'Isle of Man', 'Kiribati', 'Macao', 'Martinique', 'Mayotte', 'Montserrat', 'Myanmar', 'Nauru', 'New Caledonia', 'Niue', 'North Korea', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'Réunion', 'Saint Barthelemy', 'Saint Helena', 'Saint Martin', 'Saint Pierre & Miquelon', 'Sint Maarten', 'St. Vincent & Grenadines', 'State of Palestine', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos', 'Tuvalu', 'U.S. Virgin Islands', 'Wallis & Futuna', 'Western Sahara']

In [7]:
#1
#A
dfDecesos = pd.read_csv('data/covid19_decesos.csv', index_col="Country/Region")
#B
del dfDecesos["Lat"]
del dfDecesos["Long"]
#C
for i in range(1,461):
    dfDecesos = dfDecesos.rename(columns={dfDecesos.columns[i]:pd.to_datetime(dfDecesos.columns[i]).strftime('%d/%m/%Y') })
    
#D
del dfDecesos["Province/State"]
dfDecesos = dfDecesos.groupby(by=['Country/Region']).sum()
dfDecesos = dfDecesos.sort_values('Country/Region')
display(dfDecesos)


dfDecesosPopulation = pd.merge(dfDecesos,dfPopulation[['Population (2020)']], on="Country/Region")
display(dfDecesosPopulation)

dfDecesosPopulationUnion = pd.merge(dfDecesos,dfPopulation[['Population (2020)']], on="Country/Region", how='outer')
noEstan = []
for i in range(0,len(dfDecesosPopulationUnion.index)):
    if not (dfDecesosPopulationUnion.index[i] in dfDecesosPopulation.index):
        noEstan.append(dfDecesosPopulationUnion.index[i])

print('En las siguientes filas no se pudo realizar merge: ')
print(noEstan)

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,16/04/2021,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,2535,2539,2539,2546,2549,2557,2561,2565,2572,2582
Albania,0,0,0,0,0,0,0,0,0,0,...,2337,2340,2342,2347,2353,2358,2364,2367,2372,2378
Algeria,0,0,0,0,0,0,0,0,0,0,...,3148,3152,3155,3160,3165,3172,3181,3190,3198,3207
Andorra,0,0,0,0,0,0,0,0,0,0,...,123,123,123,123,123,123,123,123,124,124
Angola,0,0,0,0,0,0,0,0,0,0,...,560,561,561,563,565,570,572,574,577,579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0,0,0,0,0,0,0,0,0,0,...,35,35,35,35,35,35,35,35,35,35
West Bank and Gaza,0,0,0,0,0,0,0,0,0,0,...,2955,2983,3017,3047,3078,3096,3115,3138,3151,3167
Yemen,0,0,0,0,0,0,0,0,0,0,...,1108,1119,1126,1132,1138,1147,1157,1165,1175,1187
Zambia,0,0,0,0,0,0,0,0,0,0,...,1233,1234,1235,1236,1236,1238,1240,1245,1245,1246
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,1551,1552,1553,1553,1554,1555,1555,1556,1556,1557

,22/01/2020,23/01/2020,24/01/2020,25/01/2020,26/01/2020,27/01/2020,28/01/2020,29/01/2020,30/01/2020,31/01/2020,...,17/04/2021,18/04/2021,19/04/2021,20/04/2021,21/04/2021,22/04/2021,23/04/2021,24/04/2021,25/04/2021,Population (2020)
Country/Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,2539,2539,2546,2549,2557,2561,2565,2572,2582,39074280
Albania,0,0,0,0,0,0,0,0,0,0,...,2340,2342,2347,2353,2358,2364,2367,2372,2378,2877239
Algeria,0,0,0,0,0,0,0,0,0,0,...,3152,3155,3160,3165,3172,3181,3190,3198,3207,43984569
Andorra,0,0,0,0,0,0,0,0,0,0,...,123,123,123,123,123,123,123,124,124,77287
Angola,0,0,0,0,0,0,0,0,0,0,...,561,561,563,565,570,572,574,577,579,33032075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,0,0,0,0,0,0,0,0,0,0,...,1888,1905,1925,1944,1965,1987,2009,2028,2047,28421581
Vietnam,0,0,0,0,0,0,0,0,0,0,...,35,35,35,35,35,35,35,35,35,97490013
Yemen,0,0,0,0,0,0,0,0,0,0,...,1119,1126,1132,1138,1147,1157,1165,1175,1187,29935468
Zambia,0,0,0,0,0,0,0,0,0,0,...,1234,1235,1236,1236,1238,1240,1245,1245,1246,18468257
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,1552,1553,1553,1554,1555,1555,1556,1556,1557,14899771

En las siguientes filas no se pudo realizar merge:
['Burma', 'Diamond Princess', 'Kosovo', 'MS Zaandam', 'Saint Vincent and the Grenadines', 'West Bank and Gaza', 'American Samoa', 'Anguilla', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Caribbean Netherlands', 'Cayman Islands', 'Channel Islands', 'Cook Islands', 'Curaçao', 'Faeroe Islands', 'Falkland Islands', 'French Guiana', 'French Polynesia', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Hong Kong', 'Isle of Man', 'Kiribati', 'Macao', 'Martinique', 'Mayotte', 'Montserrat', 'Myanmar', 'Nauru', 'New Caledonia', 'Niue', 'North Korea', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'Réunion', 'Saint Barthelemy', 'Saint Helena', 'Saint Martin', 'Saint Pierre & Miquelon', 'Sint Maarten', 'St. Vincent & Grenadines', 'State of Palestine', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos', 'Tuvalu', 'U.S. Virgin Islands', 'Wallis & Futuna', 'Western Sahara']

### Análisis global (1.5pt)

1. Obtenga la cantidad total  a la fecha (26 de Abril) de los casos (a) confirmados, (b) cerrados (recuperados más decesos) y (c) activos (confirmados menos cerrados) por país. En base a estas cantidades calcule el porcentaje de 
    1. casos activos con respecto al total de confirmados
    1. decesos con respecto al total de casos cerrados
    1. recuperados con respecto al total de casos cerrados
1. Luego calcule las siguientes tasas en base a información a la fecha
    1. Tasa de incidencia: confirmados por 100.000 dividido población total
    1. Tasa de recuperación: recuperados por 100.000 dividido población total
    1. Tasa de mortalidad: decesos por 100.000 dividido población total
1. En base a lo anterior muestre los nombres y los valores de los 5 países con
    1. La mayor y menor tasa de incidencia, respectivamente
    1. La mayor y menor tasa de recuperación, respectivamente
    1. La mayor y menor tasa de mortalidad, respectivamente
1. Responda, analice y discuta: ¿En qué lugar/ranking se encuentra Chile con respecto a cada una de las métricas de los puntos anteriores? ¿A qué países de la [OCDE](https://es.wikipedia.org/wiki/Organizaci%C3%B3n_para_la_Cooperaci%C3%B3n_y_el_Desarrollo_Econ%C3%B3micos) se parece más? ¿A qué paises de latinoamérica se parece más?

In [8]:
NumeroConfirmadosTotal = dfConfirmadosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')]
NumeroCerradosTotal = dfDecesosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] + dfRecuperadosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')]
NumeroActivosTotal = dfConfirmadosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] - NumeroCerradosTotal

In [9]:
#A
print('Casos activos con respecto al total de confirmados \n')
ActivosRespectoConfirmados = (NumeroActivosTotal * 100) / NumeroConfirmadosTotal
display(ActivosRespectoConfirmados)
print('\n')

#B
print('Decesos con respecto al total de casos cerrados\n')
DecesosRespectoCerrados = (dfDecesos[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] * 100) / NumeroCerradosTotal
display(DecesosRespectoCerrados)
print('\n')

#C
print('Recuperados con respecto al total de casos cerrados\n')
RecuperadosRespectoCerrados = (dfRecuperados[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] * 100) / NumeroCerradosTotal
display(RecuperadosRespectoCerrados)
print('\n')

Casos activos con respecto al total de confirmados

Country/Region
Afghanistan     6.410278
Albania        17.183634
Algeria        27.634343
Andorra         3.407351
Angola          7.567652
                 ...
Venezuela       8.549588
Vietnam        10.270841
Yemen          39.172234
Zambia          0.588892
Zimbabwe        3.691645
Name: 25/04/2021, Length: 186, dtype: float64

Decesos con respecto al total de casos cerrados

Country/Region
Afghanistan            4.688493
Albania                2.199693
Algeria                3.664892
Andorra                0.982957
Angola                 2.446031
                        ...
Vietnam                1.372011
West Bank and Gaza          NaN
Yemen                 31.797482
Zambia                 1.371945
Zimbabwe               4.244820
Name: 25/04/2021, Length: 192, dtype: float64

Recuperados con respecto al total de casos cerrados

Country/Region
Afghanistan           95.311507
Albania               97.800307
Algeria               96.335108
Andorra               99.017043
Angola                97.553969
                        ...
Vietnam               98.627989
West Bank and Gaza          NaN
Yemen                 68.202518
Zambia                98.628055
Zimbabwe              95.755180
Name: 25/04/2021, Length: 192, dtype: float64

In [10]:
#2
#A
print('Tasa de incidencia \n')
TasaIncidencia = (NumeroConfirmadosTotal * 100000) / dfConfirmadosPopulation['Population (2020)']
display(TasaIncidencia)
print('\n')

#B
print('Tasa de recuperacion \n')
TasaRecuperacion = (dfRecuperadosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] * 100000) / dfRecuperadosPopulation['Population (2020)']
display(TasaRecuperacion)
print('\n')

#C
print('Tasa de Mortalidad \n')
TasaMortalidad = (dfDecesosPopulation[pd.to_datetime('2021-04-25').strftime('%d/%m/%Y')] * 100000) / dfDecesosPopulation['Population (2020)']
display(TasaMortalidad)

Tasa de incidencia

Country/Region
Afghanistan      150.592666
Albania         4536.884145
Algeria          274.919143
Andorra        16898.055300
Angola            77.527676
                   ...
Venezuela        673.847102
Vietnam            2.916196
Yemen             20.500765
Zambia           494.675811
Zimbabwe         255.614667
Length: 186, dtype: float64

Tasa de recuperacion

Country/Region
Afghanistan      134.331330
Albania         3674.633911
Algeria          191.655851
Andorra        16161.838343
Angola            69.907809
                   ...
Venezuela        609.033678
Vietnam            2.580777
Yemen              8.504961
Zambia           485.015993
Zimbabwe         235.728455
Length: 186, dtype: float64

Tasa de Mortalidad

Country/Region
Afghanistan      6.607927
Albania         82.648678
Algeria          7.291193
Andorra        160.440954
Angola           1.752842
                  ...
Venezuela        7.202274
Vietnam          0.035901
Yemen            3.965196
Zambia           6.746711
Zimbabwe        10.449825
Length: 186, dtype: float64

In [11]:
#3

#A
print('Mayor tasa de incidencia \n')
MayorTasaIncidencia = TasaIncidencia.sort_values(ascending=False)[0:5]
display(MayorTasaIncidencia)
print('\n')
print('Menor tasa de incidencia \n')
MenorTasaIncidencia = TasaIncidencia.sort_values()[0:5]
display(MenorTasaIncidencia)
print('\n')

#B
print('Mayor tasa de recuperacion \n')
MayorTasaRecuperacion = TasaRecuperacion.sort_values(ascending=False)[0:5]
display(MayorTasaRecuperacion)
print('\n')
print('Menor tasa de recuperacion \n')
MenorTasaRecuperacion = TasaRecuperacion.sort_values()[0:5]
display(MenorTasaRecuperacion)
print('\n')

#C
print('Mayor tasa de mortalidad \n')
MayorTasaMortalidad = TasaMortalidad.sort_values(ascending=False)[0:5]
display(MayorTasaMortalidad)
print('\n')
print('Menor tasa de mortalidad \n')
MenorTasaMortalidad = TasaMortalidad.sort_values()[0:5]
display(MenorTasaMortalidad)
print('\n')

Mayor tasa de incidencia

Country/Region
Andorra       16898.055300
Montenegro    15389.759266
Czechia       15116.787605
San Marino    14868.607118
Slovenia      11401.118524
dtype: float64

Menor tasa de incidencia

Country/Region
Tanzania           0.848158
Micronesia         0.867822
Vanuatu            1.297282
Samoa              1.510247
Solomon Islands    2.899933
dtype: float64

Mayor tasa de recuperacion

Country/Region
Andorra       16161.838343
Montenegro    14744.777735
San Marino    14255.833137
Czechia       14227.759190
Slovenia      10695.487085
dtype: float64

Menor tasa de recuperacion

Country/Region
Belgium     0.000000
Sweden      0.000000
US          0.000000
Serbia      0.000000
Tanzania    0.304937
dtype: float64

Mayor tasa de mortalidad

Country/Region
Hungary                   275.735780
Czechia                   270.357539
San Marino                262.196559
Bosnia and Herzegovina    250.308805
Montenegro                233.250541
dtype: float64

Menor tasa de mortalidad

Country/Region
Laos                     0.0
Holy See                 0.0
Samoa                    0.0
Saint Kitts and Nevis    0.0
Solomon Islands          0.0
dtype: float64

In [12]:
#4
PosicionChile = []
ValorChile = []

PosicionChile.append(list(ActivosRespectoConfirmados.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(ActivosRespectoConfirmados.sort_values(ascending=False)['Chile'])

PosicionChile.append(list(DecesosRespectoCerrados.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(DecesosRespectoCerrados.sort_values(ascending=False)['Chile'])

PosicionChile.append(list(RecuperadosRespectoCerrados.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(RecuperadosRespectoCerrados.sort_values(ascending=False)['Chile'])

PosicionChile.append(list(TasaIncidencia.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(TasaIncidencia.sort_values(ascending=False)['Chile'])

PosicionChile.append(list(TasaRecuperacion.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(TasaRecuperacion.sort_values(ascending=False)['Chile'])

PosicionChile.append(list(TasaMortalidad.sort_values(ascending=False).index).index('Chile'))
ValorChile.append(TasaMortalidad.sort_values(ascending=False)['Chile'])

print('Chile en casos activos con respecto al total de confirmados en orden decendente: \nse encuentra en la posicion {0} con {1}%'
      .format(PosicionChile[0],ValorChile[0]))
print('Chile en decesos con respecto al total de casos cerrados en orden decendente: \nse encuentra en la posicion {0} con {1}%'
      .format(PosicionChile[1],ValorChile[1]))
print('Chile en recuperados con respecto al total de casos cerrados en orden decendente: \nse encuentra en la posicion {0} con {1}%'
      .format(PosicionChile[2],ValorChile[2]))
print('Chile en tasa de incidencia por cada 100.000 habitantes en orden decendente: \nse encuentra en la posicion {0} con {1}'
      .format(PosicionChile[3],ValorChile[3]))
print('Chile en tasa de recuperacion por cada 100.000 habitantes en orden decendente: \nse encuentra en la posicion {0} con {1}'
      .format(PosicionChile[4],ValorChile[4]))
print('Chile en tasa de mortalidad por cada 100.000 habitantes en orden decendente: \nse encuentra en la posicion {0} con {1}'
      .format(PosicionChile[5],ValorChile[5]))

Chile en casos activos con respecto al total de confirmados en orden decendente:
se encuentra en la posicion 134 con 3.741825818102222%
Chile en decesos con respecto al total de casos cerrados en orden decendente:
se encuentra en la posicion 74 con 2.2967309602104864%
Chile en recuperados con respecto al total de casos cerrados en orden decendente:
se encuentra en la posicion 111 con 97.70326903978952%
Chile en tasa de incidencia por cada 100.000 habitantes en orden decendente:
se encuentra en la posicion 41 con 6108.958633515813
Chile en tasa de recuperacion por cada 100.000 habitantes en orden decendente:
se encuentra en la posicion 27 con 5745.315716882119
Chile en tasa de mortalidad por cada 100.000 habitantes en orden decendente:
se encuentra en la posicion 31 con 135.05632526761457

In [13]:
OCDE = ['Austria','Australia','Belgium','Canada','Chile','Colombia','Czechia','Denmark','Estonia','Finland',
        'France','Germany','Greece','Hungary','Iceland','Ireland','Israel','Italy','Japan','Korea, South',
       'Latvia','Lithuania','Luxembourg','Mexico','Netherlands','New Zealand','Norway','Poland','Portugal',
        'Slovakia','Slovenia','Spain','Sweden','Switzerland','Turkey','United Kingdom','US']

PosicionOCDE = []
ValorOCDE = []

print('Casos activos con respecto al total de confirmados \n')
ActivosRespectoConfirmadosOCDE = abs(ActivosRespectoConfirmados[OCDE] - ActivosRespectoConfirmados['Chile']).sort_values()[1:10]
display(ActivosRespectoConfirmadosOCDE)
print('\n')
print('Decesos con respecto al total de casos cerrados \n')
DecesosRespectoCerradosOCDE = abs(DecesosRespectoCerrados[OCDE] - DecesosRespectoCerrados['Chile']).sort_values()[1:10]
display(DecesosRespectoCerradosOCDE)
print('\n')
print('Recuperados con respecto al total de casos cerrados \n')
RecuperadosRespectoCerradosOCDE = abs(RecuperadosRespectoCerrados[OCDE] - RecuperadosRespectoCerrados['Chile']).sort_values()[1:10]
display(RecuperadosRespectoCerradosOCDE)
print('\n')
print('Tasa de incidencia \n')
TasaIncidenciaOCDE = abs(TasaIncidencia[OCDE] - TasaIncidencia['Chile']).sort_values()[1:10]
display(TasaIncidenciaOCDE)
print('\n')
print(' Tasa de recuperacion \n')
TasaRecuperacionOCDE = abs(TasaRecuperacion[OCDE] - TasaRecuperacion['Chile']).sort_values()[1:10]
display(TasaRecuperacionOCDE)
print('\n')
print('Tasa de mortalidad\n')
TasaMortalidadOCDE = abs(TasaMortalidad[OCDE] - TasaMortalidad['Chile']).sort_values()[1:10]
display(TasaMortalidadOCDE)
print('\n')

MasParecidoOCDE = set(list(ActivosRespectoConfirmadosOCDE.index)) & set(list(DecesosRespectoCerradosOCDE.index))
MasParecidoOCDE = MasParecidoOCDE & set(list(RecuperadosRespectoCerradosOCDE.index))
MasParecidoOCDE = MasParecidoOCDE & set(list(TasaIncidenciaOCDE.index))
MasParecidoOCDE = MasParecidoOCDE & set(list(TasaRecuperacionOCDE.index))
MasParecidoOCDE = MasParecidoOCDE & set(list(TasaMortalidadOCDE.index))

print('El pais mas parecido a chile de la OCDE es: ' + str(MasParecidoOCDE))

Casos activos con respecto al total de confirmados

Country/Region
Denmark        0.094415
Czechia        0.350782
Colombia       0.399839
Austria        0.484428
Slovenia       0.671999
Portugal       0.770739
Luxembourg     0.854656
Iceland        1.644799
New Zealand    2.473083
Name: 25/04/2021, dtype: float64

Decesos con respecto al total de casos cerrados

Country/Region
Canada      0.129291
Portugal    0.201381
Poland      0.314827
Latvia      0.338759
Japan       0.353212
Finland     0.371481
Colombia    0.386086
Germany     0.426179
Czechia     0.431954
Name: 25/04/2021, dtype: float64

Recuperados con respecto al total de casos cerrados

Country/Region
Canada      0.129291
Portugal    0.201381
Poland      0.314827
Latvia      0.338759
Japan       0.353212
Finland     0.371481
Colombia    0.386086
Germany     0.426179
Czechia     0.431954
Name: 25/04/2021, dtype: float64

Tasa de incidencia

Country/Region
Latvia              17.024681
United Kingdom     396.640728
Italy              446.763342
Turkey             629.396902
Austria            645.945579
Colombia           666.298358
Slovakia           848.979386
Ireland           1123.721330
Poland            1182.030579
dtype: float64

 Tasa de recuperacion

Country/Region
Italy        149.871781
Latvia       153.860517
Austria      612.222267
Colombia     668.041297
Poland       701.460257
Hungary      751.448184
Turkey       924.163833
Slovakia    1069.584884
Denmark     1667.969786
dtype: float64

Tasa de mortalidad

Country/Region
Sweden          2.655634
Colombia        4.912783
Lithuania       6.657051
Luxembourg      9.200826
Switzerland    13.079985
France         22.705831
Austria        23.169513
Latvia         23.390841
Spain          30.885403
dtype: float64

El pais mas parecido a chile de la OCDE es: {'Colombia'}

In [14]:
PosicionOCDE.append(list(ActivosRespectoConfirmadosOCDE.index).index('Colombia'))
ValorOCDE.append(ActivosRespectoConfirmadosOCDE['Colombia'])

PosicionOCDE.append(list(DecesosRespectoCerradosOCDE.index).index('Colombia'))
ValorOCDE.append(DecesosRespectoCerradosOCDE['Colombia'])

PosicionOCDE.append(list(RecuperadosRespectoCerradosOCDE.index).index('Colombia'))
ValorOCDE.append(RecuperadosRespectoCerradosOCDE['Colombia'])

PosicionOCDE.append(list(TasaIncidenciaOCDE.index).index('Colombia'))
ValorOCDE.append(TasaIncidenciaOCDE['Colombia'])

PosicionOCDE.append(list(TasaRecuperacionOCDE.index).index('Colombia'))
ValorOCDE.append(TasaRecuperacionOCDE['Colombia'])

PosicionOCDE.append(list(TasaMortalidadOCDE.index).index('Colombia'))
ValorOCDE.append(TasaMortalidadOCDE['Colombia'])

print('{0} en casos activos con respecto al total de confirmados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia'
      .format('Colombia',PosicionOCDE[0],ValorOCDE[0]))
print('{0} en decesos con respecto al total de casos cerrados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia'
      .format('Colombia',PosicionOCDE[1],ValorOCDE[1]))
print('{0} en recuperados con respecto al total de casos cerrados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia' 
      .format('Colombia',PosicionOCDE[2],ValorOCDE[2]))
print('{0} en tasa de incidencia por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionOCDE[3],ValorOCDE[3]))
print('{0} en tasa de recuperacion por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionOCDE[4],ValorOCDE[4]))
print('{0} en tasa de mortalidad por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionOCDE[5],ValorOCDE[5]))

Colombia en casos activos con respecto al total de confirmados en orden decendente en comparacion a Chile:
se encuentra en la posicion 2 del DataFrame, con 0.399839022385887% de diferencia
Colombia en decesos con respecto al total de casos cerrados en orden decendente en comparacion a Chile:
se encuentra en la posicion 6 del DataFrame, con 0.38608627801169737% de diferencia
Colombia en recuperados con respecto al total de casos cerrados en orden decendente en comparacion a Chile:
se encuentra en la posicion 6 del DataFrame, con 0.38608627801170314% de diferencia
Colombia en tasa de incidencia por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 5 del DataFrame, con 666.2983576948072 de diferencia
Colombia en tasa de recuperacion por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 3 del DataFrame, con 668.0412968424171 de diferencia
Colombia en tasa de mortalidad por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 1 del DataFrame, con 4.912783482797977 de diferencia

In [15]:
LATAM = ['Argentina','Bolivia','Brazil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador',
        'Guatemala','Haiti','Honduras','Mexico','Nicaragua','Panama','Paraguay','Peru','Dominican Republic',
        'Uruguay','Venezuela']

PosicionLATAM = []
ValorLATAM = []

print('Casos activos con respecto al total de confirmados \n')
ActivosRespectoConfirmadosLATAM = abs(ActivosRespectoConfirmados[LATAM] - ActivosRespectoConfirmados['Chile']).sort_values()[1:10]
display(ActivosRespectoConfirmadosLATAM)
print('\n')
print('Decesos con respecto al total de casos cerrados \n')
DecesosRespectoCerradosLATAM = abs(DecesosRespectoCerrados[LATAM] - DecesosRespectoCerrados['Chile']).sort_values()[1:10]
display(DecesosRespectoCerradosLATAM)
print('\n')
print('Recuperados con respecto al total de casos cerrados \n')
RecuperadosRespectoCerradosLATAM = abs(RecuperadosRespectoCerrados[LATAM] - RecuperadosRespectoCerrados['Chile']).sort_values()[1:10]
display(RecuperadosRespectoCerradosLATAM)
print('\n')
print('Tasa de incidencia \n')
TasaIncidenciaLATAM = abs(TasaIncidencia[LATAM] - TasaIncidencia['Chile']).sort_values()[1:10]
display(TasaIncidenciaLATAM)
print('\n')
print(' Tasa de recuperacion \n')
TasaRecuperacionLATAM = abs(TasaRecuperacion[LATAM] - TasaRecuperacion['Chile']).sort_values()[1:10]
display(TasaRecuperacionLATAM)
print('\n')
print('Tasa de mortalidad\n')
TasaMortalidadLATAM = abs(TasaMortalidad[LATAM] - TasaMortalidad['Chile']).sort_values()[1:10]
display(TasaMortalidadLATAM)
print('\n')

MasParecidoLATAM = set(list(ActivosRespectoConfirmadosLATAM.index)) & set(list(DecesosRespectoCerradosLATAM.index))
MasParecidoLATAM = MasParecidoLATAM & set(list(RecuperadosRespectoCerradosLATAM.index))
MasParecidoLATAM = MasParecidoLATAM & set(list(TasaIncidenciaLATAM.index))
MasParecidoLATAM = MasParecidoLATAM & set(list(TasaRecuperacionLATAM.index))
MasParecidoLATAM = MasParecidoLATAM & set(list(TasaMortalidadLATAM.index))

print('Los paises màs parecidos de latinoamerica son: ' + str(MasParecidoLATAM))

Casos activos con respecto al total de confirmados

Country/Region
Colombia       0.399839
El Salvador    0.879175
Cuba           1.989039
Haiti          2.138711
Panama         2.660460
Peru           2.960707
Guatemala      4.210885
Venezuela      4.807762
Brazil         5.570292
Name: 25/04/2021, dtype: float64

Decesos con respecto al total de casos cerrados

Country/Region
Argentina             0.092746
Haiti                 0.238679
Paraguay              0.319132
Colombia              0.386086
Panama                0.567407
Brazil                0.708162
Costa Rica            0.749408
Dominican Republic    0.763521
Uruguay               0.813454
Name: 25/04/2021, dtype: float64

Recuperados con respecto al total de casos cerrados

Country/Region
Argentina             0.092746
Haiti                 0.238679
Paraguay              0.319132
Colombia              0.386086
Panama                0.567407
Brazil                0.708162
Costa Rica            0.749408
Dominican Republic    0.763521
Uruguay               0.813454
Name: 25/04/2021, dtype: float64

Tasa de incidencia

Country/Region
Argentina      210.999887
Brazil         629.436807
Colombia       666.298358
Peru           778.962404
Uruguay        790.391219
Costa Rica    1429.370114
Panama        2280.827918
Paraguay      2372.267209
Bolivia       3564.909627
dtype: float64

 Tasa de recuperacion

Country/Region
Brazil         181.966157
Argentina      182.450887
Peru           637.659975
Colombia       668.041297
Uruguay       1300.666046
Costa Rica    1825.758541
Panama        2410.228888
Paraguay      2672.277993
Bolivia       3645.925510
dtype: float64

Tasa de mortalidad

Country/Region
Argentina     1.120997
Colombia      4.912783
Panama        8.461363
Bolivia      25.451427
Mexico       31.355078
Ecuador      32.295219
Peru         45.650539
Brazil       48.569910
Paraguay     52.510592
dtype: float64

Los paises màs parecidos de latinoamerica son: {'Colombia', 'Panama', 'Brazil'}

In [16]:
Brazil = []
Brazil.append(list(ActivosRespectoConfirmadosLATAM.index).index('Brazil'))
Brazil.append(list(DecesosRespectoCerradosLATAM.index).index('Brazil'))
Brazil.append(list(RecuperadosRespectoCerradosLATAM.index).index('Brazil'))
Brazil.append(list(TasaIncidenciaLATAM.index).index('Brazil'))
Brazil.append(list(TasaRecuperacionLATAM.index).index('Brazil'))
Brazil.append(list(TasaMortalidadLATAM.index).index('Brazil'))
Colombia = []
Colombia.append(list(ActivosRespectoConfirmadosLATAM.index).index('Colombia'))
Colombia.append(list(DecesosRespectoCerradosLATAM.index).index('Colombia'))
Colombia.append(list(RecuperadosRespectoCerradosLATAM.index).index('Colombia'))
Colombia.append(list(TasaIncidenciaLATAM.index).index('Colombia'))
Colombia.append(list(TasaRecuperacionLATAM.index).index('Colombia'))
Colombia.append(list(TasaMortalidadLATAM.index).index('Colombia'))
Panama = []
Panama.append(list(ActivosRespectoConfirmadosLATAM.index).index('Panama'))
Panama.append(list(DecesosRespectoCerradosLATAM.index).index('Panama'))
Panama.append(list(RecuperadosRespectoCerradosLATAM.index).index('Panama'))
Panama.append(list(TasaIncidenciaLATAM.index).index('Panama'))
Panama.append(list(TasaRecuperacionLATAM.index).index('Panama'))
Panama.append(list(TasaMortalidadLATAM.index).index('Panama'))

print('Brasil:   {0} \nColombia: {1} \nPanama:   {2}'.format(sum(Brazil),sum(Colombia),sum(Panama)))

Brasil:   26
Colombia: 12
Panama:   26

In [17]:
PosicionLATAM = Colombia
ValorLATAM.append(ActivosRespectoConfirmadosOCDE['Colombia'])
ValorLATAM.append(DecesosRespectoCerradosOCDE['Colombia'])
ValorLATAM.append(RecuperadosRespectoCerradosOCDE['Colombia'])
ValorLATAM.append(TasaIncidenciaOCDE['Colombia'])
ValorLATAM.append(TasaRecuperacionOCDE['Colombia'])
ValorLATAM.append(TasaMortalidadOCDE['Colombia'])

print('{0} en casos activos con respecto al total de confirmados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia'
      .format('Colombia',PosicionLATAM[0],ValorLATAM[0]))
print('{0} en decesos con respecto al total de casos cerrados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia'
      .format('Colombia',PosicionLATAM[1],ValorLATAM[1]))
print('{0} en recuperados con respecto al total de casos cerrados en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2}% de diferencia' 
      .format('Colombia',PosicionLATAM[2],ValorLATAM[2]))
print('{0} en tasa de incidencia por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionLATAM[3],ValorLATAM[3]))
print('{0} en tasa de recuperacion por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionLATAM[4],ValorLATAM[4]))
print('{0} en tasa de mortalidad por cada 100.000 habitantes en orden decendente en comparacion a Chile: \nse encuentra en la posicion {1} del DataFrame, con {2} de diferencia'
      .format('Colombia',PosicionLATAM[5],ValorLATAM[5]))

Colombia en casos activos con respecto al total de confirmados en orden decendente en comparacion a Chile:
se encuentra en la posicion 0 del DataFrame, con 0.399839022385887% de diferencia
Colombia en decesos con respecto al total de casos cerrados en orden decendente en comparacion a Chile:
se encuentra en la posicion 3 del DataFrame, con 0.38608627801169737% de diferencia
Colombia en recuperados con respecto al total de casos cerrados en orden decendente en comparacion a Chile:
se encuentra en la posicion 3 del DataFrame, con 0.38608627801170314% de diferencia
Colombia en tasa de incidencia por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 2 del DataFrame, con 666.2983576948072 de diferencia
Colombia en tasa de recuperacion por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 3 del DataFrame, con 668.0412968424171 de diferencia
Colombia en tasa de mortalidad por cada 100.000 habitantes en orden decendente en comparacion a Chile:
se encuentra en la posicion 1 del DataFrame, con 4.912783482797977 de diferencia

### Análisis temporal y comparativo (2.0pt)

1. Construya una interfaz gráfica usando `ipywidgets` y `matplotlib` que permita realizar comparaciones entre las series de tiempo de COVID-19 de dos países seleccionados arbitrariamente. A modo de simplificación considere sólo los países de la [OCDE](https://es.wikipedia.org/wiki/Organizaci%C3%B3n_para_la_Cooperaci%C3%B3n_y_el_Desarrollo_Econ%C3%B3micos). Requerimientos:
    1. La interfaz debe incluir controles para escoger dos países a partir de una lista
    1. La interfaz debe incluir tres [tabs](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Tabs), el primero debe mostrar las series de tiempo de ambos países de los casos confirmados, el segundo la de recuperados y el tercero la de los decesos, respectivamente. Use una leyenda para indicar el nombre de los países.
    1. La interfaz debe tener un control que permita escoger entre casos acumulados y casos nuevos  
    1. La interfaz debe tener un control que permita escoger entre valores absolutos y valores relativos (tasas por 100.000 habitantes)
    1. La interfaz debe tener un control que permita escoger entre valores diarios y valores semanales (acumulados). Para esto último se recomienda usar `groupby` con una [frecuencia lunes a lunes](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#anchored-offsets)
    
En base a su interfaz:   

1. Describa en detalle la situación de Chile con respecto a la evolución temporal de las series de tiempo. En particular destaque patrones y comportamientos que considere relevantes y compare lo que observa en las distintas series de tiempo. Considerando la evolución a nivel de semana, conteste ¿En qué fechas ocurre un aumento o disminución notoria de los casos? ¿En qué fechas hay máximos y mínimos?
1. Considerando métricas que sean relativas compare el caso de Chile contra cinco países de la OCDE seleccionados por ustedes. Destaque semejanzas y diferencias considerando las cantidades y los posibles desfases temporales existentes.

In [110]:
import ipywidgets as widgets
from ipywidgets import HBox, VBox, Button, Layout, Label
from ipywidgets import interact, interactive, fixed, interact_manual


size1 = widgets.Dropdown(description="Pais 1", options=OCDE)
size2 = widgets.Dropdown(description="Pais 2", options=OCDE)
cambio1 = widgets.Checkbox(value=False, description='Casos diarios', disabled=False, indent=True)
cambio2 = widgets.Checkbox(value=False, description='Valores relativos', disabled=False, indent=True)
cambio3 = widgets.Checkbox(value=False, description='Valores semanales', disabled=False, indent=True)


def Casos_Confirmados(size1,size2,cambio1,cambio2, cambio3):
    if not cambio1:
        dfMostrar = dfConfirmados
        if cambio3:
            columnas = list(dfMostrar.loc[:].columns[5:460:7]) + [dfMostrar.columns[459]]
            dfMostrar = dfMostrar.loc[:,columnas]
            titulo = 'Total de casos confirmados agrupados por semana\n'
        else:
            titulo = 'Total de casos confirmados\n'
    else:
        dfConfirmados2 = pd.read_csv('data/covid19_confirmados.csv', index_col="Country/Region")
        del dfConfirmados2["Lat"]
        del dfConfirmados2["Long"]
        for i in range(1,461):
            dfConfirmados2 = dfConfirmados2.rename(columns={dfConfirmados2.columns[i]:pd.to_datetime(dfConfirmados2.columns[i]).strftime('%d/%m/%Y') })
        del dfConfirmados2["Province/State"]
        dfConfirmados2 = dfConfirmados2.groupby(by=['Country/Region']).sum()
        dfConfirmados2 = dfConfirmados2.sort_values('Country/Region')
        dfConfirmados2.columns = list(dfConfirmados2.columns[1:]) +['delete']
        del dfConfirmados2["delete"]
        dfMostrar = dfConfirmados - pd.merge(pd.DataFrame(dfConfirmados[pd.to_datetime('2020-01-22').strftime('%d/%m/%Y')]),dfConfirmados2, on="Country/Region")
        dfMostrar[dfMostrar < 0] = 0
        if cambio3:
            dfMostrar2 = pd.DataFrame(dfMostrar.loc['Chile']).transpose()
            dfMostrar2.columns = pd.to_datetime(dfMostrar2.columns, dayfirst = True, errors = 'ignore')
            dfMostrar2 = dfMostrar.groupby(pd.PeriodIndex(dfMostrar2.columns, freq='W-MON'), axis=1).sum()
            dfMostrar2.columns = (list(dfMostrar.columns[5:460:7]) + [dfMostrar.columns[459]])
            dfMostrar = dfMostrar2
            titulo = 'Total de casos confirmados diarios agrupados por semana \n'
        else:
            titulo = 'Total de casos confirmados diarios \n'
    if not cambio2:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot(dfMostrar.loc[size1], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot(dfMostrar.loc[size2], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas\n', fontsize=12, fontname='serif')
    else:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot((dfMostrar.loc[size1]*100000) / dfConfirmadosPopulation.loc[size1]['Population (2020)'], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot((dfMostrar.loc[size2]*100000) / dfConfirmadosPopulation.loc[size2]['Population (2020)'], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas por cada 100.000 habitantes\n', fontsize=12, fontname='serif')
    # Leyenda
    ax.legend(loc=1, ncol=3, bbox_to_anchor=(0.5, 1))

    # Texto para ejes y título
    plt.xticks(rotation=45)
    
    if cambio3:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::2]) + [dfMostrar.columns[65]] )
    else:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::17]))
        
    ax.set_xlabel('\nFecha', fontsize=14, fontname='serif')
    ax.set_title(titulo, fontsize=18, fontname='serif')
    # Grilla
    ax.grid(color="g", which="major", axis='both', linestyle=':', linewidth=0.5)
    
    pass

def Recuperados(size1,size2,cambio1,cambio2, cambio3):
    if not cambio1:
        dfMostrar = dfRecuperados
        if cambio3:
            columnas = list(dfMostrar.loc[:].columns[5:460:7]) + [dfMostrar.columns[459]]
            dfMostrar = dfMostrar.loc[:,columnas]
            titulo = 'Total de casos recuperados agrupados por semana\n'
        else:
            titulo = 'Total de casos recuperados\n'
    else:
        dfRecuperados2 = pd.read_csv('data/covid19_recuperados.csv', index_col="Country/Region")
        del dfRecuperados2["Lat"]
        del dfRecuperados2["Long"]
        for i in range(1,461):
            dfRecuperados2 = dfRecuperados2.rename(columns={dfRecuperados2.columns[i]:pd.to_datetime(dfRecuperados2.columns[i]).strftime('%d/%m/%Y') })
        del dfRecuperados2["Province/State"]
        dfRecuperados2 = dfRecuperados2.groupby(by=['Country/Region']).sum()
        dfRecuperados2 = dfRecuperados2.sort_values('Country/Region')
        dfRecuperados2.columns = list(dfRecuperados2.columns[1:]) +['delete']
        del dfRecuperados2["delete"]
        dfMostrar = dfRecuperados - pd.merge(pd.DataFrame(dfRecuperados[pd.to_datetime('2020-01-22').strftime('%d/%m/%Y')]),dfRecuperados2, on="Country/Region")
        dfMostrar[dfMostrar < 0] = 0
        if cambio3:
            dfMostrar2 = pd.DataFrame(dfMostrar.loc['Chile']).transpose()
            dfMostrar2.columns = pd.to_datetime(dfMostrar2.columns, dayfirst = True, errors = 'ignore')
            dfMostrar2 = dfMostrar.groupby(pd.PeriodIndex(dfMostrar2.columns, freq='W-MON'), axis=1).sum()
            dfMostrar2.columns = (list(dfMostrar.columns[5:460:7]) + [dfMostrar.columns[459]])
            dfMostrar = dfMostrar2
            titulo = 'Total de casos recuperados diarios agrupados por semana \n'
        else:
            titulo = 'Total de casos recuperados diarios \n'
    if not cambio2:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot(dfMostrar.loc[size1], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot(dfMostrar.loc[size2], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas\n', fontsize=12, fontname='serif')
    else:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot((dfMostrar.loc[size1]*100000) / dfConfirmadosPopulation.loc[size1]['Population (2020)'], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot((dfMostrar.loc[size2]*100000) / dfConfirmadosPopulation.loc[size2]['Population (2020)'], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas por cada 100.000 habitantes\n', fontsize=12, fontname='serif')
    # Leyenda
    ax.legend(loc=1, ncol=3, bbox_to_anchor=(0.5, 1))

    # Texto para ejes y título
    plt.xticks(rotation=45)
    
    if cambio3:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::2]) + [dfMostrar.columns[65]] )
    else:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::17]))
        
    ax.set_xlabel('\nFecha', fontsize=14, fontname='serif')
    ax.set_title(titulo, fontsize=18, fontname='serif')
    # Grilla
    ax.grid(color="g", which="major", axis='both', linestyle=':', linewidth=0.5)
    pass

def  Decesos(size1,size2,cambio1,cambio2, cambio3):
    if not cambio1:
        dfMostrar = dfDecesos
        if cambio3:
            columnas = list(dfMostrar.loc[:].columns[5:460:7]) + [dfMostrar.columns[459]]
            dfMostrar = dfMostrar.loc[:,columnas]
            titulo = 'Total de decesos agrupados por semana\n'
        else:
            titulo = 'Total de decesos\n'
    else:
        dfDecesos2 = pd.read_csv('data/covid19_decesos.csv', index_col="Country/Region")
        del dfDecesos2["Lat"]
        del dfDecesos2["Long"]
        for i in range(1,461):
            dfDecesos2 = dfDecesos2.rename(columns={dfDecesos2.columns[i]:pd.to_datetime(dfDecesos2.columns[i]).strftime('%d/%m/%Y') })
        del dfDecesos2["Province/State"]
        dfDecesos2 = dfDecesos2.groupby(by=['Country/Region']).sum()
        dfDecesos2 = dfDecesos2.sort_values('Country/Region')
        dfDecesos2.columns = list(dfDecesos2.columns[1:]) +['delete']
        del dfDecesos2["delete"]
        dfMostrar = dfDecesos - pd.merge(pd.DataFrame(dfDecesos[pd.to_datetime('2020-01-22').strftime('%d/%m/%Y')]),dfDecesos2, on="Country/Region")
        dfMostrar[dfMostrar < 0] = 0
        if cambio3:
            dfMostrar2 = pd.DataFrame(dfMostrar.loc['Chile']).transpose()
            dfMostrar2.columns = pd.to_datetime(dfMostrar2.columns, dayfirst = True, errors = 'ignore')
            dfMostrar2 = dfMostrar.groupby(pd.PeriodIndex(dfMostrar2.columns, freq='W-MON'), axis=1).sum()
            dfMostrar2.columns = (list(dfMostrar.columns[5:460:7]) + [dfMostrar.columns[459]])
            dfMostrar = dfMostrar2
            titulo = 'Total de decesos diarios agrupados por semana \n'
        else:
            titulo = 'Total de decesos diarios \n'
    if not cambio2:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot(dfMostrar.loc[size1], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot(dfMostrar.loc[size2], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas\n', fontsize=12, fontname='serif')
    else:
        fig, ax = plt.subplots(figsize=(14, 8.75), tight_layout=True, facecolor='w')
        ax.plot((dfMostrar.loc[size1]*100000) / dfConfirmadosPopulation.loc[size1]['Population (2020)'], # datos
                linewidth=2, # Ancho de la linea
                alpha=0.75, # Opacidad
                label=size1) # Etiqueta para la leyenda
        ax.plot((dfMostrar.loc[size2]*100000) / dfConfirmadosPopulation.loc[size2]['Population (2020)'], 
                linewidth=2, alpha=0.75, label=size2)
        ax.set_ylabel('Número de personas por cada 100.000 habitantes\n', fontsize=12, fontname='serif')
    # Leyenda
    ax.legend(loc=1, ncol=3, bbox_to_anchor=(0.5, 1))

    # Texto para ejes y título
    plt.xticks(rotation=45)
    
    if cambio3:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::2]) + [dfMostrar.columns[65]] )
    else:
        ax.set_xticks(list(dfMostrar.loc[size1].index[::17]))
        
    ax.set_xlabel('\nFecha', fontsize=14, fontname='serif')
    ax.set_title(titulo, fontsize=18, fontname='serif')
    # Grilla
    ax.grid(color="g", which="major", axis='both', linestyle=':', linewidth=0.5)
    pass


out1 = widgets.interactive(Casos_Confirmados, size1=size1, size2=size2, cambio1=cambio1, cambio2=cambio2, cambio3=cambio3)
out2 = widgets.interactive(Recuperados, size1=size1, size2=size2, cambio1=cambio1, cambio2=cambio2, cambio3=cambio3)
out3 = widgets.interactive(Decesos, size1=size1, size2=size2, cambio1=cambio1, cambio2=cambio2, cambio3=cambio3)

tab  = widgets.Tab(children = [out1, out2,out3])
tab.set_title(0,  'Casos confirmados')
tab.set_title(1, 'Recuperados')
tab.set_title(2, 'Decesos')


display(tab)

Tab(children=(interactive(children=(Dropdown(description='Pais 1', options=('Austria', 'Australia', 'Belgium',…